version: '3.8'

services:
  web:
    build: .
    container_name: cv-portfolio
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app/static:/app/app/static
    networks:
      - cv-network

networks:
  cv-network:
    driver: bridge